# Site Settings
title: Seattle Snowmass 2022
tagline: US Particle Physics will meet in person from July 17-27, 2022 in Seattle to conclude the Snowmass 2022 Process.
email: gwatts@uw.edu
description: >
  US Particle Physics will meet in person from July 17-27, 2022 in Seattle to conclude the Snowmass 2022 Process

# baseurl: "http://seattlesnowmass2021.net"
url: "http://seattlesnowmass2021.net"

permalink: pretty

disqus:
  # Leave shortname blank to disable comments site-wide.
  shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# sass:
#   style: compressed
#   source_dir: _sass

google_analytics: UA-179008494-1

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      show_sidebar: false
      hide_hero: true

remote_theme: chrisrhymes/bulma-clean-theme
